"""Signal dataclass used by the backtest engine.

The shape mirrors the dict produced by ``MultiExchangeAnalyzer.generate_signal``
in ``main.py`` and consumed by ``signal_stats.SignalStatistics.add_signal``,
so signals from the live scanner can be replayed on history without
translation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Mapping


@dataclass(frozen=True)
class Signal:
    """A trading signal generated by a strategy or by the live scanner.

    Attributes:
        timestamp: Bar timestamp at which the signal was generated.
            The signal is treated as actionable starting from the *next* bar
            to avoid look-ahead bias.
        symbol: Market symbol, e.g. ``"BTC/USDT"``.
        direction: ``"LONG"`` or ``"SHORT"`` (case-insensitive on input).
        entry_price: Limit/intended entry price. The engine fills at the next
            bar's open by default; ``entry_price`` is used for R:R reporting.
        stop_loss: Absolute stop-loss price. Required.
        target_1: First take-profit price. Required.
        target_2: Optional second take-profit price (``None`` if not used).
        signal_power: Free-form qualitative power label (e.g. ``"strong"``).
        signal_strength: Numeric confidence score, 0-100.
        reasons: Human-readable list of reasons (audit trail).
        meta: Arbitrary metadata kept for reporting.
    """

    timestamp: datetime
    symbol: str
    direction: str
    entry_price: float
    stop_loss: float
    target_1: float
    target_2: float | None = None
    signal_power: str = ""
    signal_strength: float = 0.0
    reasons: tuple[str, ...] = field(default_factory=tuple)
    meta: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        normalized = self.direction.upper()
        if normalized not in {"LONG", "SHORT"}:
            raise ValueError(
                f"direction must be LONG or SHORT, got {self.direction!r}"
            )
        # frozen dataclass — assign via object.__setattr__
        object.__setattr__(self, "direction", normalized)

        if self.entry_price <= 0:
            raise ValueError("entry_price must be positive")
        if self.stop_loss <= 0:
            raise ValueError("stop_loss must be positive")
        if self.target_1 <= 0:
            raise ValueError("target_1 must be positive")
        if self.target_2 is not None and self.target_2 <= 0:
            raise ValueError("target_2 must be positive when provided")

        if normalized == "LONG":
            if self.stop_loss >= self.entry_price:
                raise ValueError("LONG stop_loss must be below entry_price")
            if self.target_1 <= self.entry_price:
                raise ValueError("LONG target_1 must be above entry_price")
        else:
            if self.stop_loss <= self.entry_price:
                raise ValueError("SHORT stop_loss must be above entry_price")
            if self.target_1 >= self.entry_price:
                raise ValueError("SHORT target_1 must be below entry_price")

    @property
    def is_long(self) -> bool:
        return self.direction == "LONG"

    @property
    def risk_pct(self) -> float:
        """Risk per unit as a positive fraction of entry price."""
        if self.is_long:
            return (self.entry_price - self.stop_loss) / self.entry_price
        return (self.stop_loss - self.entry_price) / self.entry_price

    @property
    def reward_pct(self) -> float:
        """Reward per unit at target_1 as a positive fraction of entry price."""
        if self.is_long:
            return (self.target_1 - self.entry_price) / self.entry_price
        return (self.entry_price - self.target_1) / self.entry_price

    @property
    def risk_reward(self) -> float:
        """R:R ratio computed against target_1."""
        risk = self.risk_pct
        if risk == 0:
            return float("inf")
        return self.reward_pct / risk

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "Signal":
        """Build a Signal from the live-scanner dict shape.

        The live scanner uses keys ``price``, ``target_1``, ``target_2``,
        ``stop_loss``, ``direction``, ``signal_power``, ``signal_strength``,
        ``reasons``. Timestamps come from ``created_at`` (ISO-8601) when
        replaying ``signals_database.json``.
        """
        ts_raw = data.get("timestamp") or data.get("created_at")
        if ts_raw is None:
            raise ValueError("Signal dict needs 'timestamp' or 'created_at'")
        if isinstance(ts_raw, datetime):
            ts = ts_raw
        else:
            ts = datetime.fromisoformat(str(ts_raw))

        entry = data.get("entry_price") or data.get("price")
        if entry is None:
            raise ValueError("Signal dict needs 'entry_price' or 'price'")

        reasons = tuple(data.get("reasons") or ())
        meta = {
            k: v
            for k, v in data.items()
            if k
            not in {
                "timestamp",
                "created_at",
                "symbol",
                "direction",
                "price",
                "entry_price",
                "stop_loss",
                "target_1",
                "target_2",
                "signal_power",
                "signal_strength",
                "reasons",
            }
        }
        return cls(
            timestamp=ts,
            symbol=str(data["symbol"]),
            direction=str(data["direction"]).upper().split()[-1],
            entry_price=float(entry),
            stop_loss=float(data["stop_loss"]),
            target_1=float(data["target_1"]),
            target_2=float(data["target_2"]) if data.get("target_2") else None,
            signal_power=str(data.get("signal_power", "")),
            signal_strength=float(data.get("signal_strength", 0) or 0),
            reasons=reasons,
            meta=meta,
        )
